apply plugin: 'com.android.application'

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "br.com.jmsistemas.automac"
    compileSdkVersion 34

    defaultConfig {
        applicationId "br.com.jmsistemas.automac"
        minSdkVersion 22
        targetSdkVersion 34
        versionCode 11
        versionName "10.1.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'] ?: "../../vendapro.jks")
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias'] ?: "upload"
                keyPassword keystoreProperties['keyPassword']
            } else {
                storeFile file("../../vendapro.jks")
                storePassword System.getenv("KEYSTORE_PASSWORD") ?: "SUA_SENHA"
                keyAlias System.getenv("KEY_ALIAS") ?: "upload"
                keyPassword System.getenv("KEY_PASSWORD") ?: "SUA_SENHA"
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
}
